{% set name = "kazu" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kazu-{{ version }}.tar.gz
  sha256: 756cc79fae6a2057f5f6595362431c2e2908ce34b020936e0a0715c34c0c0471

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - spacy >=3.2.2
    - pytorch >=2.0.0
    - transformers >=4.0.0
    - rdflib >=6.0.0
    - requests >=2.20.0
    - hydra-core >=1.3.0
    - pandas >=1.0.0
    - pyahocorasick
    - pymongo >=4.3.3
    - rapidfuzz >=1.0.0
    - scikit-learn >=0.24.0
    - scipy <1.12.0
    - regex >=2020.1.7
    - psutil >=5.3.0
    - cachetools >=5.2.0
    - diskcache >=5.4.0
    - cattrs >=23.2.0
    - tqdm

test:
  imports:
    - kazu
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://astrazeneca.github.io/KAZU/
  summary: Biomedical Named Entity Recognition and Entity Linking for Enterprise use cases
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - kazu/ontology_matching/LICENSE
  dev_url: https://github.com/AstraZeneca/KAZU
  doc_url: https://astrazeneca.github.io/KAZU/

extra:
  recipe-maintainers:
    - peterbygrave
