{% set name = "kazu" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kazu-{{ version }}.tar.gz
  sha256: 93938788f0fe8567e2189079005172f01cf7eacef75d8da91abbeb1c0dd45c6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - spacy >=3.2.2
    - pytorch >=2.0.0
    - transformers >=4.0.0
    - rdflib >=6.0.0
    - requests >=2.20.0
    - hydra-core >=1.3.0
    - pandas >=1.0.0
    - pyahocorasick
    - pymongo >=4.3.3
    - rapidfuzz >=1.0.0
    - scikit-learn >=0.24.0
    - scipy <1.12.0
    - regex >=2020.1.7
    - psutil >=5.3.0
    - cachetools >=5.2.0
    - diskcache >=5.4.0
    - cattrs >=23.2.0
    - tqdm

test:
  imports:
    - kazu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://astrazeneca.github.io/KAZU/
  summary: Biomedical Named Entity Recognition and Entity Linking for Enterprise use cases
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - kazu/ontology_matching/LICENSE
  dev_url: https://github.com/AstraZeneca/KAZU
  doc_url: https://astrazeneca.github.io/KAZU/

extra:
  recipe-maintainers:
    - peterbygrave
